### ISSUE TITLE
Use EmbedBox in an actual project

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/embed-box#76]
(Now that https://github.com/EagerIO/EmbedBox/issues/58 is closed 😉 .... )

Perhaps on https://eager.io/showcase/SmartUnderline/?
Maybe on http://github.hubspot.com/pace/docs/welcome/ with plugins for WordPress Eager Pace, etc.?

@zackbloom @TeffenEllis thoughts?

**Comment by TeffenEllis** [comment]
I think the both are a fantastic idea, especially Pace.

At some point I'd love to get Eager's plugin install UI using EmbedBox.
